with open('input/maze_map0.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x S        xxx   x            x\n')
    outfile.write('x xx xxxx      x x  xxxxxxxx  x\n')
    outfile.write('x x   x xxxxxxxx    x   x  x  x\n')
    outfile.write('x xxx x        xxxxxx  xx  x  x\n')
    outfile.write('x       xxxxx  xT   x  x      x\n')
    outfile.write('x xxxxxxx  x   x    x  x   xxxx\n')
    outfile.write('x x        x        x  xx  x  x\n')
    outfile.write('x x  xxxx  xxxxxxxxxx   x  x  x\n')
    outfile.write('x x   Tx       x x x  x    x  x\n')
    outfile.write('xxxxxxxx    x  x      x x  x  x\n')
    outfile.write('x      x    x  x xxx  x x  x  x\n')
    outfile.write('xxx         x  xxx      xxxx  x\n')
    outfile.write('x   x       x        xx        \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')


with open('input/level_1/input2.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n')
    outfile.write('x S        xxx   x            x\n')
    outfile.write('x xx xxxx      x x  xxxxxxxx  x\n')
    outfile.write('x x   x xxxxxxxx    x   x  x  x\n')
    outfile.write('x xxx x x      x xxxx  xx  x  x\n')
    outfile.write('x       x xxx  x    x  x      x\n')
    outfile.write('x xxxxxxx  x   x    x  x   xxxx\n')
    outfile.write('x x        x        x  xx  x  x\n')
    outfile.write('x x        xxxxxxxxxx   x  x  x\n')
    outfile.write('x x            x x x  x    x  x\n')
    outfile.write('xxxxxxxx    x  x      x x  x  x\n')
    outfile.write('x      x    x  x xxx  x x  x  x\n')
    outfile.write('xxx         x  xxx      xxxx  x\n')
    outfile.write('x   x       x        xx        \n')
    outfile.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')

with open('input/level_1/input4.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxx\n')
    outfile.write('x S      x\n')
    outfile.write('x   xx   x\n')
    outfile.write('x   xx   x\n')
    outfile.write('x        x\n')
    outfile.write('x   xxx  x\n')
    outfile.write('x   x x  x\n')
    outfile.write('x   xxx  x\n')
    outfile.write('x        x\n')
    outfile.write('xxxxxxxx x\n')

with open('input/level_1/input3.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxx\n')
    outfile.write('x     xx  \n')
    outfile.write('x     x  x\n')
    outfile.write('x  x Sx  x\n')
    outfile.write('x  x     x\n')
    outfile.write('x  xxxx  x\n')
    outfile.write('x   x x xx\n')
    outfile.write('x   xxx  x\n')
    outfile.write('x        x\n')
    outfile.write('xxxxxxxxxx\n')

with open('input/level_1/input5.txt', 'w') as outfile:
    outfile.write('0\n')
    outfile.write('xxxxxxxxxx\n')
    outfile.write('x     xx  \n')
    outfile.write('x     x  x\n')
    outfile.write('x  xxSx  x\n')
    outfile.write('x  x     x\n')
    outfile.write('x  xxxx  x\n')
    outfile.write('x   x x xx\n')
    outfile.write('x   xxx  x\n')
    outfile.write('x        x\n')
    outfile.write('xxxxxxxxxx\n')